### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Hous2019** [SensorsIot/ESP32-ULP-Arduino-IDE#1]
Dear Andreas,
I get an error running your ULP sketch. 
I highly appreciate if you could indicate what goes wrong. Hope this is possible.
Note: I am a complete novice in programming/electronics but thanks to your video's I succeed to make a BLE connected scale/load cell. New great worlds opened to me: Arduino, ESP32, HX711, etc. Thank you so much! 

The message I get while Verifying the sketch in Arduino is:

Arduino: 1.8.5 (Mac OS X), Board: "ESP32 Dev Module, Disabled, Default, QIO, 80MHz, 4MB (32Mb), 921600, None"

Archiving built core (caching) in: /var/folders/h3/9xsf827d2z3fdc3jh5qr42m80000gn/T/arduino_cache_145050/core/core_esp32_esp32_esp32_PSRAM_disabled,PartitionScheme_default,FlashMode_qio,FlashFreq_80,FlashSize_4M,UploadSpeed_921600,DebugLevel_none_7e6a80fff8650d5cdd133cad74069fee.a
Traceback (most recent call last):
  File "/Users/HOUS2019/Library/Arduino15/packages/esp32/hardware/esp32/1.0.0/tools/sdk/include/ulp/esp32ulp_build_recipe.py", line 407, in <module>
    main(sys.argv[1:])
  File "/Users/HOUS2019/Library/Arduino15/packages/esp32/hardware/esp32/1.0.0/tools/sdk/include/ulp/esp32ulp_build_recipe.py", line 93, in main
    build_ulp(bpath, ppath, xpath, upath, ulp_files, board_options)
  File "/Users/HOUS2019/Library/Arduino15/packages/esp32/hardware/esp32/1.0.0/tools/sdk/include/ulp/esp32ulp_build_recipe.py", line 118, in build_ulp
    proc = subprocess.Popen(cmd[1],stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
exit status 1
Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Hous2019** [comment]
Dear Andreas,

issue solved!
With some persistence (as often the case with software) succeeded to fix the issue.
Continue the journey to explore the ULP.

Best regards
Hous
